Repository micro-nova/AmpliPi, pull requests merged in 2021-03, with the labels that each got.

#82 Add AmpliPi trademarks policy
  TRADEMARKS.md
Labels: documentation

#83 Add Nginx Unit Webserver
  amplipi/rt.py
  amplipi/wsgi.py
  config/update_config.bash
  config/update_web.bash
  config/webserver.conf
  debs/README.md
  debs/unit-python3.7-dbg_1.22.0-1~buster_armhf.deb
  debs/unit-python3.7_1.22.0-1~buster_armhf.deb
  debs/unit_1.22.0-1~buster_armhf.deb
  docs/amplipi_api.yaml
  scripts/deploy
  scripts/deploy_web_only
  scripts/run_debug_webserver
Labels: enhancement

#89 Update webapp footer
  web/static/css/style.css
  web/templates/index.html
Labels: webapp

#79 Add DLNA streams
  amplipi/ctrl.py
  amplipi/streams.py
  config/dlna_metadata.bash
  config/update_config.bash
  docs/amplipi_api.yaml
  scripts/deploy
  scripts/dlna_meta.py
  scripts/sp_meta.py
  web/static/js/script.js
Labels: streaming
